# Generated by Django 5.2.4 on 2025-08-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
